### ISSUE TITLE
Using Hash#slice forces ruby 2.5+

### ISSUE THREAD

**Issue by hkmaly** [beanstalkd/beaneater#83]
The slice method was added in ruby 2.5+. On ruby 2.3 it causes this error:
```
NoMethodError: undefined method `slice' for {}:Hash
        /var/lib/gems/2.3.0/gems/beaneater-1.1.1/lib/beaneater/connection.rb:73:in `transmit'
        /var/lib/gems/2.3.0/gems/beaneater-1.1.1/lib/beaneater/tube/collection.rb:33:in `transmit'
        /var/lib/gems/2.3.0/gems/beaneater-1.1.1/lib/beaneater/tube/collection.rb:79:in `all'
```

If that's deliberate, ok, but I would expect explicit mention on README. If it's not (and seems it's only slice in whole code), you may want to re-think https://github.com/beanstalkd/beaneater/commit/13e97917f1bd9db92fa3e0c0c7af1227784995bd

**Comment by nesquena** [comment]
Thanks for raising this, I think we would definitely want to remove the use of slice in the code. 

Would one you be open to preparing a simple patch? cc @albb0920 @hkmaly 

I'd be happy to merge and release a patch update. However I wonder if there are other reasons the code wouldn't work prior to Ruby 2.5. 

Alternatively I'd be happy to add a note to the readme specifying this library now only works with Ruby 2.5 or above

**Comment by albb0920** [comment]
Ruby 2.3 has long been EoL-ed, I don't think time should be spent on making EoL-ed ruby work.
As this well make supporting new versions more hard.
https://www.ruby-lang.org/en/downloads/branches/

Time should be spent instead on refreshing the code and make it work well with ruby 3.0
A mention in README that we only test against supported versions of ruby should be enough.

**Comment by hkmaly** [comment]
Hmmm ... ok, it didn't get through tests, maybe I don't understand the code as much as I though.

**Comment by nesquena** [comment]
If it's as simple a fix as https://github.com/beanstalkd/beaneater/pull/84 to support 2.3, then I am all for it. However, I am also fine adding a note that this only works with 2.5 and above especially given that 2.3 was EOL in 2019
